server {
    listen 80;
    server_name localhost;

    # 前端文件
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API请求转发
    location /api/ {
        proxy_pass http://http-download-server:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}